name: simple_dart_multilang_controller
description: Multilang support for Simple Dart UI framework
version: 0.0.1
repository: https://github.com/simple-dart/multilang_controller
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'
